name: Default network configuration
stages:
  initramfs:
    - name: Setup network
      files:
        - path: /etc/netplan/elemental_setup.yaml
          content: |
            network:
              version: 2
              renderer: networkd
              ethernets:
                eth0:
                  dhcp4: true
          permissions: 384
          owner: 0
          group: 0
        - path: /etc/ssh/sshd_config.d/root_login.conf
          content: |
            PermitRootLogin yes
          permissions: 384
          owner: 0
          group: 0
        - path: /etc/udev/rules.d/70-persistent-net.rules
          content: >
            SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="?*",
            ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="?*", NAME="eth0"
          permissions: 384
          owner: 0
          group: 0
      commands:
        - ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
        - netplan apply

  # Make /var/lib/docker persistent
  rootfs.after:
    - name: "Immutable Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/etc /var"
        PERSISTENT_STATE_PATHS: >-
          /etc/docker
          /etc/systemd
          /etc/ssh
          /home
          /opt
          /root
          /var/lib/docker
          /var/log
        PERSISTENT_STATE_BIND: "true"

  network:
    - name: Performance optimizations
      sysctl:
        fs.file-max: '1000000000'
        fs.inotify.max_user_instances: '1024'
        fs.inotify.max_user_watches: '1048576'
        net.core.somaxconn: '4096'
        net.ipv4.tcp_retries2: '5'
        vm.dirty_background_ratio: '5'
        vm.dirty_ratio: '15'
        vm.dirty_expire_centisecs: '500'
        vm.dirty_writeback_centisecs: '100'
        vm.overcommit_memory: '1'
        vm.max_map_count: '262144'
        vm.min_free_kbytes: '65536'
        vm.swappiness: '0'

    - name: "Load kernel modules"
      files:
      modules:
        - nf_nat
